org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

loom.ignoreDependencyLoomVersionValidation=true

mod_id=mermod
mod_version=4.0.1
maven_group=io.github.thatpreston
archives_name=mermod
enabled_platforms=fabric,neoforge

mod_name=Mermod
mod_description=Mermod adds a magical necklace that transforms you into a merperson in water!
mod_license=MPL-2.0

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)

fabric_loader_version=0.18.4
fabric_api_version=0.141.3+1.21.11

neoforge_version=21.11.38-beta
neoforge_version_range=[21.11,)
neoforge_loader_version_range=[1,)

architectury_api_version=19.0.1

curios_version=14.0.0+1.21.11
trinkets_version=3.11.0-beta.2+1.21.11
cca_version=7.3.0

figura_version=0.1.5+1.21.8
luaj_version=3.0.8
nv_websocket_version=2.14

fcap_version=21.11.1
cloth_config_version=21.11.153
modmenu_version=17.0.0-beta.2

sodium_version=0.8.6+mc1.21.11
iris_version=1.10.6+1.21.11