org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

loom.ignoreDependencyLoomVersionValidation=true

mod_id=mermod
mod_version=4.0.1
maven_group=io.github.thatpreston
archives_name=mermod
enabled_platforms=fabric,neoforge

mod_name=Mermod
mod_description=Mermod adds a magical necklace that transforms you into a merperson in water!
mod_license=MPL-2.0

minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2)

fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2

neoforge_version=26.1.2.84
neoforge_version_range=[26.1,)
neoforge_loader_version_range=[1,)

architectury_api_version=20.0.9

curios_version=15.0.0+26.1.2
trinkets_version=4.0.0-beta.3+26.1
cca_version=8.0.1

fcap_version=26.1.5
cloth_config_version=26.1.154
modmenu_version=18.0.0

sodium_version=0.9.1+mc26.1.2
iris_version=1.11.2+26.1