org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_id=mermod
mod_version=3.0.1
maven_group=io.github.thatpreston
archives_name=mermod
enabled_platforms=fabric,forge

mod_name=Mermod
mod_description=Mermod adds a magical necklace that transforms you into a merperson in water!
mod_license=MPL-2.0

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

fabric_loader_version=0.15.10
fabric_api_version=0.92.0+1.20.1

forge_version=1.20.1-47.4.10
forge_version_range=[47,)

connector_version=1.0.0-beta.48+1.20.1
forgified_fabric_api_version=0.92.6+1.11.14+1.20.1

architectury_api_version=9.2.14

curios_version=5.9.1+1.20.1
trinkets_version=3.7.2

figura_version=0.1.4+1.20.1
luaj_version=3.0.8
nv_websocket_version=2.14

fcap_version=8.0.0
cloth_config_version=11.1.118
modmenu_version=7.2.2