architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    modCompileOnly "org.figuramc:figura-common-intermediary:$rootProject.figura_version"
    compileOnly "com.github.FiguraMC.luaj:luaj-core:$rootProject.luaj_version-figura"
    compileOnly "com.github.FiguraMC.luaj:luaj-jse:$rootProject.luaj_version-figura"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-common:$rootProject.fcap_version"
    modCompileOnly "me.shedaniel.cloth:cloth-config:$rootProject.cloth_config_version"
    modCompileOnly "maven.modrinth:origins:1.10.2+mc.1.20.1"
    modCompileOnly "io.github.apace100:apoli-2.9.2-mc.1.20.1:2.9.2+mc.1.20.x"
}